version: '3.8'

services:
  # API Gateway
  gateway:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - GATEWAY_HOST=0.0.0.0
      - GATEWAY_PORT=8000
      - GATEWAY_DEBUG=true
      - USER_SERVICE_DATABASE_URL=postgresql://postgres:password@postgres:5432/gateway_users
      - PRODUCT_SERVICE_DATABASE_URL=postgresql://postgres:password@postgres:5432/gateway_products
      - ORDER_SERVICE_DATABASE_URL=mongodb://mongo:27017/gateway_orders
      - USER_SERVICE_REDIS_URL=redis://redis:6379/1
      - PRODUCT_SERVICE_ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - postgres
      - redis
      - mongo
      - elasticsearch
    networks:
      - gateway-network
    restart: unless-stopped

  # PostgreSQL for user and product services
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - gateway-network
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gateway-network
    restart: unless-stopped

  # MongoDB for order service
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - gateway-network
    restart: unless-stopped

  # Elasticsearch for product search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - gateway-network
    restart: unless-stopped

  # Kibana for Elasticsearch visualization (optional)
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - gateway-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  mongo_data:
  elasticsearch_data:

networks:
  gateway-network:
    driver: bridge
