gateway:
  host: "0.0.0.0"
  port: 7777
  debug: true
  title: "Unified API Gateway"
  version: "1.0.0"
  description: "Dynamic API Gateway with modular service integration"
  
services:
  docman_service:
    # Document management service configuration
    database_url: "postgresql://localhost/docman_db"
    minio_endpoint: "localhost:9000"
    minio_access_key: "minioadmin"
    minio_secret_key: "minioadmin"
    minio_bucket: "documents"
    qdrant_url: "http://localhost:6333"
    log_level: "INFO"